[tool.poetry]
name = "mqtt_linux"
version = "0.0.1"
description = "owo.digital mqtt Linux client"
authors = ["Octelly (Eli Štefků) <eli@stefek.cz>"]

[tool.poetry.scripts]
mqtt-linux = 'mqtt_linux:app'

[tool.poetry.dependencies]
python = "^3.12"
monitorcontrol = "^3.1.0"
paho-mqtt = "^2.1.0"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
isort = "^5.13.2"
pyright = "^1.1.342"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
