# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/968d9816-7be0-49bf-811a-4f2bf372ff9e";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/CE63-D923";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  boot.loader.efi.efiSysMountPoint = lib.mkForce "/boot"; # :(

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/ab98f669-a702-47e2-9de5-fe4cabc1b272";
      fsType = "btrfs";
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/c1a11e66-ad65-4c06-a81c-6ba0a208d491";
      fsType = "btrfs";
      options = [
        "noatime"
      ];
    };

  fileSystems."/tmp" =
    {
      device = "none";
      fsType = "tmpfs";
      options = [
        "defaults"
        "size=150%"
      ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/c3e7f63d-4c66-4def-a9d0-ad202a3c8a95"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp42s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
