# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
# TODO: This format file is obsolete, consider migrating to JSON.

{ fetchNuGet }:
[
  (fetchNuGet {
    pname = "Avalonia";
    version = "11.2.4";
    hash = "sha256-CcdWUxqd43A4KeY1K4T5M6R1M0zuwdwyd5Qh/BAlNT4=";
  })
  (fetchNuGet {
    pname = "Avalonia.Angle.Windows.Natives";
    version = "2.1.22045.20230930";
    hash = "sha256-RxPcWUT3b/+R3Tu5E5ftpr5ppCLZrhm+OTsi0SwW3pc=";
  })
  (fetchNuGet {
    pname = "Avalonia.BuildServices";
    version = "0.0.31";
    hash = "sha256-wgtodGf644CsUZEBIpFKcUjYHTbnu7mZmlr8uHIxeKA=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.ColorPicker";
    version = "11.2.4";
    hash = "sha256-21Wfb4p0dCevw8Iu/Fchngt1teAnBaxEWgiUpFkerTo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.DataGrid";
    version = "11.2.4";
    hash = "sha256-fqQBKzHcL0CwuOQ90Gp+UUZZP9OQ9U6H41bvikxQJpo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Desktop";
    version = "11.2.4";
    hash = "sha256-WKTOx7RNSb0fOMg5Za4j+u9DwKXDqVzHwQCEXSm7TFo=";
  })
  (fetchNuGet {
    pname = "Avalonia.Diagnostics";
    version = "11.2.4";
    hash = "sha256-MUSfRXeJ1bstO2rTqWWCQyVq2EpjM5b5bxe0KxVAEU4=";
  })
  (fetchNuGet {
    pname = "Avalonia.Fonts.Inter";
    version = "11.2.4";
    hash = "sha256-2VlA1tucYnWMA04D3sBdgwqrfKciTzmC9poSDyElHBY=";
  })
  (fetchNuGet {
    pname = "Avalonia.FreeDesktop";
    version = "11.2.4";
    hash = "sha256-lw8YFXR/pn0awFvFW+OhjZ2LbHonL6zwqLIz+pQp+Sk=";
  })
  (fetchNuGet {
    pname = "Avalonia.HtmlRenderer";
    version = "11.0.0";
    hash = "sha256-DBD113eQJNHeEgFmx/tVRSnHxhGBQIKWVKxr1QRilr4=";
  })
  (fetchNuGet {
    pname = "Avalonia.Native";
    version = "11.2.4";
    hash = "sha256-MvxivGjYerXcr70JpWe9CCXO6MU9QQgCkmZfjZCFdJM=";
  })
  (fetchNuGet {
    pname = "Avalonia.Remote.Protocol";
    version = "11.2.4";
    hash = "sha256-mKQVqtzxnZu6p64ZxIHXKSIw3AxAFjhmrxCc5/1VXfc=";
  })
  (fetchNuGet {
    pname = "Avalonia.Skia";
    version = "11.2.4";
    hash = "sha256-82UQGuCl5hN5kdA3Uz7hptpNnG1EPlSB6k/a6XPSuXI=";
  })
  (fetchNuGet {
    pname = "Avalonia.Themes.Fluent";
    version = "11.2.4";
    hash = "sha256-CPun/JWFCVoGxgMA510/gMP2ZB9aZJ9Bk8yuNjwo738=";
  })
  (fetchNuGet {
    pname = "Avalonia.Themes.Simple";
    version = "11.2.4";
    hash = "sha256-rnF2/bzN8AuOFlsuekOxlu+uLI7n1kIAmC36FFXMKak=";
  })
  (fetchNuGet {
    pname = "Avalonia.Win32";
    version = "11.2.4";
    hash = "sha256-LJSKiLbdof8qouQhN7pY1RkMOb09IiAu/nrJFR2OybY=";
  })
  (fetchNuGet {
    pname = "Avalonia.X11";
    version = "11.2.4";
    hash = "sha256-qty8D2/HlZz/7MiEhuagjlKlooDoW3fow5yJY5oX4Uk=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "7.3.0.3";
    hash = "sha256-1vDIcG1aVwVABOfzV09eAAbZLFJqibip9LaIx5k+JxM=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Linux";
    version = "7.3.0.3";
    hash = "sha256-HW5r16wdlgDMbE/IfE5AQGDVFJ6TS6oipldfMztx+LM=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "7.3.0.3";
    hash = "sha256-UpAVfRIYY8Wh8xD4wFjrXHiJcvlBLuc2Xdm15RwQ76w=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.WebAssembly";
    version = "7.3.0.3";
    hash = "sha256-jHrU70rOADAcsVfVfozU33t/5B5Tk0CurRTf4fVQe3I=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "7.3.0.3";
    hash = "sha256-v/PeEfleJcx9tsEQAo5+7Q0XPNgBqiSLNnB2nnAGp+I=";
  })
  (fetchNuGet {
    pname = "ini-parser";
    version = "2.5.2";
    hash = "sha256-IGUP2iEBuL8QpcllvPfeuqn7O908H16Kg0oOrXUUJ3Y=";
  })
  (fetchNuGet {
    pname = "MicroCom.Runtime";
    version = "0.11.0";
    hash = "sha256-VdwpP5fsclvNqJuppaOvwEwv2ofnAI5ZSz2V+UEdLF0=";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.Primitives";
    version = "5.0.1";
    hash = "sha256-e4uoLnUSmON4If9qJh78+4z14IzW9qCu5YkqLdQqWQU=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.3";
    hash = "sha256-hy/BieY4qxBWVVsDqqOPaLy1QobiIapkbrESm6v2PHc=";
  })
  (fetchNuGet {
    pname = "Semver";
    version = "3.0.0";
    hash = "sha256-nX5ka27GY6pz9S73H6sLSQCrnAyyI9xDVdzrtlMp4BQ=";
  })
  (fetchNuGet {
    pname = "SharpCompress";
    version = "0.39.0";
    hash = "sha256-Me88MMn5NUiw5bugFKCKFRnFSXQKIFZJ+k97Ex6jgZE=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.9";
    hash = "sha256-jZ/4nVXYJtrz9SBf6sYc/s0FxS7ReIYM4kMkrhZS+24=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.9";
    hash = "sha256-mQ/oBaqRR71WfS66mJCvcc3uKW7CNEHoPN2JilDbw/A=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.9";
    hash = "sha256-qvGuAmjXGjGKMzOPBvP9VWRVOICSGb7aNVejU0lLe/g=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.WebAssembly";
    version = "2.88.9";
    hash = "sha256-vgFL4Pdy3O1RKBp+T9N3W4nkH9yurZ0suo8u3gPmmhY=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.9";
    hash = "sha256-kP5XM5GgwHGfNJfe4T2yO5NIZtiF71Ddp0pd1vG5V/4=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.6.0";
    hash = "sha256-c2QlgFB16IlfBms5YLsTCFQ/QeKoS6ph1a9mdRkq/Jc=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "8.0.0";
    hash = "sha256-LdpB1s4vQzsOODaxiKstLks57X9DTD5D6cPx8DE1wwE=";
  })
  (fetchNuGet {
    pname = "Tmds.DBus.Protocol";
    version = "0.20.0";
    hash = "sha256-CRW/tkgsuBiBJfRwou12ozRQsWhHDooeP88E5wWpWJw=";
  })
  (fetchNuGet {
    pname = "ZstdSharp.Port";
    version = "0.8.4";
    hash = "sha256-4bFUNK++6yUOnY7bZQiibClSJUQjH0uIiUbQLBtPWbo=";
  })
]
